# Generated by Django 5.0.1 on 2024-01-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_carouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
    ]
