# Generated by Django 5.0.3 on 2024-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_bookimage_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
