# Generated by Django 5.0.1 on 2024-01-26 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_district_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/default-shop-image.jpg', upload_to='shops-image/')),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
    ]
