# Generated by Django 5.1.1 on 2024-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
