# Generated by Django 5.0.1 on 2024-01-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='login',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
