# Generated by Django 5.0.1 on 2024-01-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user',
            new_name='shop',
        ),
    ]
