# Generated by Django 5.0.1 on 2024-01-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_user_token_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
