# Generated by Django 5.0.1 on 2024-01-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_token_shop_delete_shop_delete_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
