# Generated by Django 5.0.1 on 2024-01-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
